[package]
name = "hell-orm"
version = "0.1.0"
edition = "2024"

[dependencies]
hell-orm-macro = { path = "../hell-orm-macro", version = "0.1.0" }
rusqlite = { version = "0.37.0", features = ["bundled"] }

